runtime: python27
threadsafe: true
api_version: 1

env_variables:
  # The following values are to be replaced by information from the output of
  # 'gcloud endpoints services deploy swagger.json' command.
  ENDPOINTS_SERVICE_NAME: megan-158015.appspot.com
  ENDPOINTS_SERVICE_VERSION: 2018-07-31r0


handlers:
# The endpoints handler must be mapped to /_ah/api.
- url: /_ah/api/.*
  script: main.api

- url: /api-docs
  static_files: static/meganv1openapi.json
  upload: static/meganv1openapi.json

- url: /api
  static_files: static/swagger-ui.html
  upload: static/swagger-ui.html

- url: /s/(.*)
  static_files: static/\1
  upload: static/.

builtins:
- deferred: on

libraries:
- name: pycrypto
  version: 2.6
- name: ssl
  version: 2.7.11


skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?setuptools/script \(dev\).tmpl$
